# https://taskfile.dev

version: '3'

tasks:
  # =============================
  # 🚀 Production build and run
  # =============================
  build:
    desc: "Build the production Docker image"
    dir: app
    cmds:
      - docker build -t rabi-food:latest
    silent: false

  # =============================
  # 🏗️ Infrastructure services
  # =============================
  infra:
    desc: "Start the infrastructure services (Grafana, Prometheus, Loki, Alloy)"
    dir: infra
    cmds:
      - docker compose -f docker-compose.infra.yaml up -d
    silent: false

  infra-down:
    desc: "Stop the infrastructure"
    dir: infra
    cmds:
      - docker compose -f docker-compose.infra.yaml down
    silent: true

  # =============================
  # 🧪 Tests and utilities
  # =============================
  infra-test:
    desc: "Start only the infrastructure for tests (Postgres, pgAdmin)"
    dir: infra
    dotenv: ["../.env.test"]
    cmds:
      - docker compose -f docker-compose.infra-test.yaml up -d postgres pgadmin
    silent: false

  infra-test-down:
    desc: "Stop the test infrastructure"
    dir: infra
    dotenv: ["../.env.test"]
    cmds:
      - docker compose -f docker-compose.infra-test.yaml down
    silent: true

  mockgen:
    desc: "Generate mocks using mockery"
    dir: app
    cmds:
      - go run github.com/vektra/mockery/v2@v2.53.5 --all --output fixtures/mocks
    silent: false

  test:
    desc: "Start the test environment"
    dir: app
    dotenv: ["../.env.test"]
    deps: [infra-test]
    cmds:
      - go clean -testcache
      - go run gotest.tools/gotestsum@v1.13.0 --format testname -- ./... -p 1 -v
    silent: false

  # =============================
  # 🔧 Infrastructure utils
  # =============================
  validate_alloy:
    desc: "Validate the Alloy configuration"
    dir: infra
    cmds:
      - docker run --rm -v $(pwd)/alloy.config.alloy:/etc/alloy/alloy.config.alloy grafana/alloy:latest validate /etc/alloy/alloy.config.alloy

  logs:
    desc: "Watch application logs"
    dir: infra
    cmds:
      - docker compose logs -f app
    interactive: true

  clean_docker:
    desc: "Prune all system and container resources"
    cmds:
      - docker system prune -a --volumes -f