# https://taskfile.dev

version: '3'

tasks:
  # =============================
  # 🚀 Production build and run
  # =============================
  build:
    desc: "Build the production Docker image"
    dir: app
    cmds:
      - docker build -t rabi-food:latest
    silent: false

  # =============================
  # 🏗️ Infrastructure services
  # =============================
  infra:
    desc: "Start the infrastructure services (Grafana, Prometheus, Loki, Alloy)"
    dir: infra
    cmds:
      - docker compose -f docker-compose.infra.yaml up -d
    silent: false

  infra-down:
    desc: "Stop the infrastructure"
    dir: infra
    cmds:
      - docker compose -f docker-compose.infra.yaml down
    silent: true

  # =============================
  # 🧪 Tests and utilities
  # =============================
  test-infra:
    desc: "Start only the infrastructure for tests (Postgres, pgAdmin)"
    dir: infra
    dotenv: ["../.env.test"]
    cmds:
      - docker compose -f docker-compose.test.yaml up -d postgres pgadmin
    silent: false

  test:
    desc: "Start the test environment"
    dir: infra
    dotenv: ["../.env.test"]
    deps: [test-infra]
    cmds:
      - docker compose -f docker-compose.test.yaml up app --build --force-recreate
    silent: false



  # =============================
  # 🔧 Infrastructure utils
  # =============================
  validate_alloy:
    desc: "Validate the Alloy configuration"
    dir: infra
    cmds:
      - docker run --rm -v $(pwd)/alloy.config.alloy:/etc/alloy/alloy.config.alloy grafana/alloy:latest validate /etc/alloy/alloy.config.alloy

  logs:
    desc: "Watch application logs"
    dir: infra
    cmds:
      - docker compose logs -f app
    interactive: true
