groups:
- name: log-errors
  rules:
  - alert: LogErrorDetected
    expr: count_over_time({job="docker"} |= "error" [5m]) > 0
    for: 30s
    labels:
      severity: warning
    annotations:
      summary: "Erro detectado em logs"
      description: "Foram detectados erros nos últimos 5 minutos."
