services:
  app-test:
    image: golang:1.25-alpine
    container_name: app-test
    env_file:
      - ../.env.test
    environment:
      - TEST_DATABASE_HOST=postgres
    volumes:
      - ../app:/app
    working_dir: /app
    networks:
      - test
    command: go run gotest.tools/gotestsum@v1.13.0 --format testname -- ./... -p 1 -v

networks:
  test:
    external: true
    name: test