version: "3.9"

services:
  app:
    image: minha-imagem:latest
    container_name: app
    ports:
      - "3000:3000"
    environment:
      - ENV=production
      - PORT=3000
      - AUTH_SECRET=${AUTH_SECRET}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_PORT=${DATABASE_PORT}
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    restart: always
    depends_on:
      - alloy
    networks:
      - observability

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3100:3100"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - loki
    restart: unless-stopped
    networks:
      - observability

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3200:3200"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki-data:/loki
    restart: unless-stopped
    networks:
      - observability

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - prometheus-data:/prometheus
    depends_on:
      - loki
    restart: unless-stopped
    networks:
      - observability

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    command: ["run", "/etc/alloy/alloy.config.alloy"]
    volumes:
      - ./alloy.config.alloy:/etc/alloy/alloy.config.alloy:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - loki
      - prometheus
    restart: unless-stopped
    networks:
      - observability

volumes:
  grafana-data:
  prometheus-data:
  loki-data:

networks:
  observability:
    driver: bridge
