services:
  app:
    image: rabi-food:${TAG}
    container_name: app
    build:
      context: ../app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - ENV=${ENV}
      - APP_PORT=${APP_PORT}
      - AUTH_SECRET=${AUTH_SECRET}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_PORT=${DATABASE_PORT}
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    restart: always
    depends_on:
      - alloy
    networks:
      - observability
