auth_enabled: false

server:
  http_listen_port: 3200

ingester:
  wal:
    enabled: true
    dir: /loki/wal

limits_config:
  ingestion_rate_mb: 32
  ingestion_burst_size_mb: 64

schema_config:
  configs:
    - from: 2024-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
    shared_store: filesystem
  filesystem:
    directory: /loki/chunks
