global:
  scrape_interval: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - "alerts.yaml"

scrape_configs:
  - job_name: "alloy"
    static_configs:
      - targets: ["alloy:12345"]

  - job_name: "app"
    static_configs:
      - targets: ["host.docker.internal:3000"]  # seu app Go, Node, etc.
