FROM golang:1.25-alpine

WORKDIR /app

RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download

COPY . .

ENV AIR_POLL=true
ENV AIR_POLL_INTERVAL=500ms

EXPOSE 3000

CMD ["air", "-c", ".air.toml"]
