FROM golang:1.25.3-bookworm

ENV GOOS=linux GOARCH=amd64
ENV PATH="/go/bin:${PATH}"

RUN apt-get update && apt-get install -y git

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

RUN go install github.com/vektra/mockery/v2@v2.53.5
RUN go install gotest.tools/gotestsum@latest

COPY . .

EXPOSE 3000
