name: Linter

on:
  pull_request:
    branches:
      - main
      - dev
      - staging

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'app/go.mod' # Use the Go version specified in go.mod
          cache: true

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v8.0.0
        with:
          working-directory: app
          version: v2.5.0

      - name: Run golangci-lint with Reviewdog
        uses: reviewdog/action-golangci-lint@v2
        with:
          workdir: app
          github_token: ${{ secrets.GITHUB_TOKEN }}
          golangci_lint_flags: --timeout=5m
          level: warning
          reporter: github-pr-review # Make a comment on the PR
          fail_level: any
