name: Security

on:
  pull_request:
    branches:
      - main
      - dev
      - staging

jobs:
  gosec:
    name: runner / gosec
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'app/go.mod'
          cache: true

      - name: Run Gosec
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          gosec -fmt sarif -out results.sarif ./...

      - name: Upload Gosec SARIF report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: app/results.sarif
