name: Security

on:
  pull_request:
    branches:
      - main
      - dev
      - staging

jobs:
  gosec:
    name: runner / gosec
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'app/go.mod'
          cache: true

      - name: Run Gosec
        uses: securego/gosec@master
        with:
          args: ./... -fmt=sarif -out=gosec.sarif

      - name: Upload Gosec SARIF report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gosec.sarif
