name: Test

on:
  pull_request:
    branches:
      - main
      - dev
      - staging

jobs:
  Test:
    runs-on: ubuntu-latest
    container: golang:1.25.0
    env:
      APP_PORT: 3000
      TEST_DATABASE_HOST: postgres
      TEST_DATABASE_USER: postgres
      TEST_DATABASE_PASSWORD: postgres

    services:
      postgres:
        image: postgres:17.6-bookworm
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Fetch Repository
        uses: actions/checkout@v3

      - name: Run Test
        run: |
          go run gotest.tools/gotestsum@latest --format testname -- ./... -p 1 -v