name: Test

on:
  pull_request:
    branches:
      - main
      - dev
      - staging

jobs:
  Test:
    runs-on: ubuntu-latest
    # We can't use actions/setup-go@v6 (or later) due to a known networking issue.
    # When using it, the Go process loses DNS access to service containers (like postgres).
    container: golang:1.25.3

    defaults:
      run:
        working-directory: app

    env:
      APP_PORT: 3000
      TEST_DATABASE_HOST: postgres
      TEST_DATABASE_USER: postgres
      TEST_DATABASE_NAME: rabi_food_test
      TEST_DATABASE_PASSWORD: postgres
      TEST_DATABASE_PORT: 5432

    services:
      postgres:
        image: postgres:17.6-bookworm
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
          POSTGRES_PORT: 5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Fetch Repository
        uses: actions/checkout@v5

      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@latest

      - name: Run Tests
        run: |
          gotestsum --format testname -- ./... -p 1 -v